version: "2"
services:
  db: 
    image: postgres
    ports:
     - 5432:5432
  
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db

  app:
    restart: always
    build: ./
    volumes: 
      - .:/tmp/pythonTornadoDocker
    ports:
      - 8889:8889
    
    depends_on:
     - db

  pgAdmin:
    image: fenglc/pgadmin4
    ports:
      - 5050:5050
    environment:
      - DEFAULT_USER=test
      - DEFAULT_PASSWORD=test
      - DEFAULT_SERVER=localhost
    links:
      - db