version: "2"
services:
  db: 
    image: postgres
  app:
    restart: always
    build: ./
    volumes: 
      - .:/tmp/pythonTornadoDocker
    ports:
      - 8889:8889
    
    depends_on:
     - db
