version: "2"
services:
  db: 
    image: postgres
   
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db

    ports:
      - 5010:5432

  app:
    restart: always
    build: ./
    volumes: 
      - .:/tmp/pythonTornadoDocker
    ports:
      - 8889:8889
    
    depends_on:
     - db
